# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 08:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161118_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.Client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='paid',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='total',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
