# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 08:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161118_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='paid',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='total',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
