# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20161118_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
