# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161118_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
