# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20161118_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['begin']},
        ),
    ]
