# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 07:50
from __future__ import unicode_literals

from django.db import migrations
import vishleva.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20161120_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=vishleva.models.NullableEmailField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
