# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20161120_1050'),
        ('events', '0007_auto_20161118_1817'),
    ]

    operations = [
    ]
