# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20161121_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='social_url',
            field=models.URLField(blank=True, help_text='social profile url (vk, facebook, ect)', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=30, unique=True),
        ),
    ]
