# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20161121_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'not confirmed'), ('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=15),
            preserve_default=False,
        ),
    ]
