# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
