# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_google_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_calendar_id',
            field=models.CharField(blank=True, db_index=True, help_text='google calendar event id', max_length=255, null=True),
        ),
    ]
