# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20161201_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expenses',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
