# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name_plural': 'Sms'},
        ),
        migrations.AlterField(
            model_name='sms',
            name='text',
            field=models.TextField(db_index=True, max_length=255),
        ),
    ]
