# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20170318_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='client',
        ),
    ]
