# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0015_event_notified_at'),
        ('mailing', '0004_remove_sms_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='events.Client'),
        ),
    ]
