# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_sms_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Sms'},
        ),
    ]
