# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_sms_send_before'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['-created_at', '-send_at'], 'verbose_name_plural': 'Sms'},
        ),
        migrations.AlterField(
            model_name='sms',
            name='send_before',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
