# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('keywords', models.CharField(max_length=255, verbose_name='keywords')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
