# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photos',
            new_name='photo',
        ),
    ]
