# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170116_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
