# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170117_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryextended',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
