# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_galleryextended_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryextended',
            name='order',
        ),
    ]
