# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_galleryextended_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryextended',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
