"""
Django settings for vishleva project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from datetime import date, timedelta
from urllib.parse import quote

from celery.schedules import crontab
from django.core.urlresolvers import reverse_lazy

# Local settings
try:
    from vishleva.local_settings import *
except ImportError:
    pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'photologue',
    'sortedm2m',
    'debug_toolbar',
    'compressor',
    'django_extensions',
    'reversion',
    'daterange_filter',
    'ordered_model',
    'rainbowtests',

    # vishleva apps
    'vishleva',
    'pages',
    'mailing',
    'events'
]
MIDDLEWARE_CLASSES = [
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'vishleva.middleware.AdminLocaleMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'vishleva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'vishleva/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vishleva.wsgi.application'

TEST_RUNNER = 'rainbowtests.test.runner.RainbowDiscoverRunner'
TEST_RUNNER = 'rainbowtests.test.runner.RainbowDiscoverRunner'
# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru'

LANGUAGES = (('ru', 'Russian'), ('en', 'English'), )

ADMIN_LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'Europe/Moscow'

DATETIME_FORMAT = "N j, Y, P"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

INTERNAL_IPS = ['127.0.0.1']

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'vishleva/static'),
                    os.path.join(BASE_DIR, 'node_modules'), )
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder')
FIXTURE_DIRS = (os.path.join(BASE_DIR, 'fixtures'), )
LOCALE_PATHS = (os.path.join(os.path.dirname(__file__), "locale"),
                os.path.join(os.path.dirname(__file__), "app_locale"), )

EMAIL_SUBJECT_PREFIX = '[vishleva.com]: '

# Two factor auth
LOGIN_URL = 'two_factor:login'

LOGOUT_URL = "admin:logout"

# Celery
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_SEND_TASK_ERROR_EMAILS = True
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_ALWAYS_EAGER = False
CELERYBEAT_SCHEDULE = {
    'event_notifications_task': {
        'task': 'events.tasks.event_notifications_task',
        'schedule': crontab(minute=0, hour='11,15,19,22')
    },
    'event_autoclose_task': {
        'task': 'events.tasks.event_autoclose_task',
        'schedule': crontab(minute=0, hour='1')
    },
}

# Django phonenumber
PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'RU'

# Tests
TEST_RUNNER = 'rainbowtests.test.runner.RainbowDiscoverRunner'

# Vishleva.com
SITE_START_DATE = date(2015, 3, 28)
PHOTOS_PER_PAGE = 20
EVENTS_CALENDAR_PERIOD = 45
